In [1]:
#fas-정재환
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
import numpy as np
import csv
import json
import seaborn as sns
%matplotlib inline 

In [2]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("NHIS_OPEN_GJ_2017_3.csv", encoding='cp949', nrows=50000)
df

Unnamed: 0     번호  성별  연령   신장   체중  허리둘레  수축기혈압  이완기혈압   식전혈당  총콜레스테롤  \
0               0      1   1  40  170   75  90.0  120.0   80.0   99.0   193.0   
1               1      2   1  35  180   80  89.0  130.0   82.0  106.0   228.0   
2               2      3   1  45  165   75  91.0  120.0   70.0   98.0   136.0   
3               3      4   1  55  175   80  91.0  145.0   87.0   95.0   201.0   
4               4      5   1  55  165   60  80.0  138.0   82.0  101.0   199.0   
...           ...    ...  ..  ..  ...  ...   ...    ...    ...    ...     ...   
49995       49995  50055   2  50  160   80  93.0  142.0   94.0   99.0   279.0   
49996       49996  50056   1  50  165   60  84.5  130.0   90.0   98.0   226.0   
49997       49997  50057   1  30  175   65  74.0  128.0   81.0   97.0   204.0   
49998       49998  50058   1  30  165   55  70.0  108.0   69.0   81.0   173.0   
49999       49999  50059   1  40  170  100  98.2  138.0   88.0   99.0   197.0   

       흡연상태  음주여부  
0       1.0   1.0  
1       3.0   0.0  
2       1.0   0.0  
3       1.0   0.0  
4       1.0   0.0  
...     ...   ...  
49995   1.0   0.0  
49996   2.0   1.0  
49997   3.0   1.0  
49998   1.0   1.0  
49999   1.0   0.0  

[50000 rows x 13 columns]

In [4]:
X = df[['체중', '신장', '허리둘레']]
Y = df[['성별']]
# 훈련 세트, 테스트 세트 준비
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, 
                                                    random_state=15)

In [5]:
print(X_train.shape)
print(X_test.shape)

(33500, 3)
(16500, 3)


In [6]:
from sklearn.preprocessing import MinMaxScaler
# 최솟값, 최댓값 분석기
scaler = MinMaxScaler()

In [7]:
# 스케일 조정
scaler.fit(X_train)

MinMaxScaler()

In [8]:
# 훈련 데이터 변환
X_train_scaled = scaler.transform(X_train)
print("변환된 후 크기: {}".format(X_train_scaled.shape))
print("스케일 조정 전 특성별 최솟값:\n {}".format(X_train.min(axis=0)))
print("스케일 조정 전 특성별 최댓값:\n {}".format(X_train.max(axis=0)))
print("스케일 조정 후 특성별 최솟값:\n {}".format(X_train_scaled.min(axis=0)))
print("스케일 조정 후 특성별 최댓값:\n {}".format(X_train_scaled.max(axis=0)))

변환된 후 크기: (33500, 3)
스케일 조정 전 특성별 최솟값:
 체중       30.0
신장      130.0
허리둘레     49.0
dtype: float64
스케일 조정 전 특성별 최댓값:
 체중      140.0
신장      190.0
허리둘레    999.0
dtype: float64
스케일 조정 후 특성별 최솟값:
 [0. 0. 0.]
스케일 조정 후 특성별 최댓값:
 [1. 1. 1.]


In [9]:
# 테스트 데이터 변환
X_test_scaled = scaler.transform(X_test)
print("스케일 조정 후 특성별 최솟값:\n {}".format(X_test_scaled.min(axis=0)))
print("스케일 조정 후 특성별 최댓값:\n {}".format(X_test_scaled.max(axis=0)))

스케일 조정 후 특성별 최솟값:
 [ 0.04545455  0.08333333 -0.01473684]
스케일 조정 후 특성별 최댓값:
 [0.86363636 1.         0.08105263]


In [10]:
# 테스트 데이터의 스케일을 조정한 결과 일부 특성은 0~1범위를 벗어났다
# 왜냐하면 transform메소드는 테스트 세트의 최솟값을 사용하지 않고 
# 훈련 세트의 최솟값을 빼고 훈련 세트의 범위로 나누기 때문이다

In [11]:
# StandardScaler를 사용해 fit과 transform을 동시에 사용
#위의 방법보다 더 좋은 습관
from sklearn.preprocessing import StandardScaler

X = df[['체중', '신장', '허리둘레']]
Y = df[['성별']]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, 
                                                    random_state=15)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [12]:
print("변환된 후 크기: {}".format(X_train_scaled.shape))
print("스케일 조정 전 특성별 최솟값:\n {}".format(X_train.min(axis=0)))
print("스케일 조정 전 특성별 최댓값:\n {}".format(X_train.max(axis=0)))
print("스케일 조정 후 특성별 최솟값:\n {}".format(X_train_scaled.min(axis=0)))
print("스케일 조정 후 특성별 최댓값:\n {}".format(X_train_scaled.max(axis=0)))

변환된 후 크기: (33500, 3)
스케일 조정 전 특성별 최솟값:
 체중       30.0
신장      130.0
허리둘레     49.0
dtype: float64
스케일 조정 전 특성별 최댓값:
 체중      140.0
신장      190.0
허리둘레    999.0
dtype: float64
스케일 조정 후 특성별 최솟값:
 [-2.65095915 -3.46445169 -2.48714559]
스케일 조정 후 특성별 최댓값:
 [ 6.13178648  2.98360622 70.8868839 ]


In [13]:
# 테스트 세트에서는 fit_transform을 사용하면 안된다. 
# 기존의 훈련세트에서 학습한 내용이 사라진다

In [14]:
# SVS 모델 준비. SVS를 학습시킬때 MinMaxScaler의 효과를 확인해보자
from sklearn.svm import SVC

X = df[['체중', '신장', '허리둘레']]
Y = df[['성별']]
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, random_state=0)

svm = SVC(C=100) # C가 클수록 허용정도가 작아지기 때문에 경계가 정교해진다
svm.fit(X_train, Y_train) # 스케일 조정
print("테스트 세트 정확도: {:.2f}".format(svm.score(X_test, Y_test)))

c:\users\jeongjh\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


테스트 세트 정확도: 0.88


In [15]:
# SVC 모델을 학습시키기 전에 MinMaxScaler로 스케일 조정
# 0~1 사이로 스케일 조정
scaler = MinMaxScaler()
scaler.fit(X_train) # 스케일 조정
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 조정된 데이터로 SVM 학습
svm.fit(X_train_scaled, Y_train)

#스케일 조정된 테스트 세트의 정확도
print("스케일 조정된 테스트 세트의 정확도: {:.2f}"
      .format(svm.score(X_test_scaled, Y_test)))

c:\users\jeongjh\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


스케일 조정된 테스트 세트의 정확도: 0.88


In [16]:
# 평균 0, 분산 1을 갖도록 스케일 조정
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)  # 스케일 조정
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 조정된 데이터로 SVM 학습
svm.fit(X_train_scaled, Y_train)

#스케일 조정된 테스트 세트의 정확도
print("스케일 조정된 테스트 세트의 정확도: {:.2f}"
      .format(svm.score(X_test_scaled, Y_test)))

c:\users\jeongjh\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


스케일 조정된 테스트 세트의 정확도: 0.88
